language: node_js
node_js:
  - "6"
  - "5.0"
  - "4"
  - "4.0"
  - "0.12"
  - "0.11"
  - "iojs"
before_script:
  - npm install -g grunt-cli
script: grunt default
notifications:
  slack: apertomove:qzb7KetNfmkBO2uYM6j9YY5E
